steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/SeSeSeven/vertex_test.git', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA']

images:
  - 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY  # 或者您可以选择 NONE
