steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/SeSeSeven/vertex_test.git /workspace

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA', '/workspace']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA']

images:
  - 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
