steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/SeSeSeven/vertex_test.git', '.']
    env:
      - 'GITHUB_TOKEN=$(github_token)'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA']

images:
  - 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA'

secrets:
- kmsKeyName: projects/dtumlops/locations/global/keyRings/my-keyring/cryptoKeys/my-key
  secretEnv:
    github_token: projects/dtumlops/secrets/github-token/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY
