steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://$(GITHUB_TOKEN)@github.com/SeSeSeven/vertex_test.git .
    secretEnv: ['GITHUB_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA']

images:
  - 'gcr.io/dtumlops/mnist-training-image:$COMMIT_SHA'

secrets:
- kmsKeyName: projects/dtumlops/locations/global/keyRings/my-keyring/cryptoKeys/my-key
  secretEnv:
    GITHUB_TOKEN: projects/dtumlops/secrets/github-token/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY
