steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [
      '-c', 
      'mkdir -p /workspace/src && git clone https://github.com/SeSeSeven/vertex_test.git /workspace/src'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops-425312/mnist-training-image:$COMMIT_SHA', '/workspace/src']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops-425312/mnist-training-image:$COMMIT_SHA']

images:
  - 'gcr.io/dtumlops-425312/mnist-training-image:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
